---
asyncapi: '3.0.0'
info:
  title: Client Configuration
  version: 1.x
  description: Client Configuration domain events
defaultContentType: application/json

channels:
  control-plane:
    title: Control Plane
    description: Events related to configuration changes
    messages:
      client-int:
        $ref: '#/components/messages/client-int'
      client-prod:
        $ref: '#/components/messages/client-prod'
      client-disabled:
        $ref: '#/components/messages/client-disabled'
      campaign-int:
        $ref: '#/components/messages/campaign-int'
      campaign-prod:
        $ref: '#/components/messages/campaign-prod'
      campaign-disabled:
        $ref: '#/components/messages/campaign-disabled'

components:
  messages:
    client-int:
      name: client-int
      title: Client INT
      summary: "A client configuration targeted at INT has been published."
      contentType: application/json
      payload:
        allOf:
          - $ref: './cloud-events-envelope-1.0.yaml'
          - $ref: './events/client-int.yaml'
      examples:
        - payload:
            $ref: './examples/client-int.json'
    client-prod:
      name: client-prod
      title: Client PROD
      summary: "A client configuration targeted at PROD has been published."
      contentType: application/json
      payload:
        allOf:
          - $ref: './cloud-events-envelope-1.0.yaml'
          - $ref: './events/client-prod.yaml'
    client-disabled:
      name: client-disabled
      title: Client Disabled
      summary: "A client configuration has been disabled in all environments."
      contentType: application/json
      payload:
        allOf:
          - $ref: './cloud-events-envelope-1.0.yaml'
          - $ref: './events/client-disabled.yaml'
    campaign-int:
      name: campaign-int
      title: Campaign INT
      summary: "A campaign configuration targeted at INT has been published."
      contentType: application/json
      payload:
        allOf:
          - $ref: './cloud-events-envelope-1.0.yaml'
          - $ref: './events/campaign-int.yaml'
    campaign-prod:
      name: campaign-prod
      title: Campaign PROD
      summary: "A campaign configuration targeted at PROD has been published."
      contentType: application/json
      payload:
        allOf:
          - $ref: './cloud-events-envelope-1.0.yaml'
          - $ref: './events/campaign-prod.yaml'
    campaign-disabled:
      name: campaign-disabled
      title: Campaign Disabled
      summary: "A campaign configuration has been disabled in all environments."
      contentType: application/json
      payload:
        allOf:
          - $ref: './cloud-events-envelope-1.0.yaml'
          - $ref: './events/campaign-disabled.yaml'
