---
asyncapi: '3.0.0'
info:
  title: Client Configuration
  version: 1.x
  description: Client Configuration domain events
defaultContentType: application/json

channels:
  control-plane:
    title: Control Plane
    description: Events related to configuration changes
    messages:
      client-published-int:
        $ref: '#/components/messages/client-published-int'
      client-published-prod:
        $ref: '#/components/messages/client-published-prod'
      client-disabled:
        $ref: '#/components/messages/client-disabled'
      campaign-published-int:
        $ref: '#/components/messages/campaign-published-int'
      campaign-published-prod:
        $ref: '#/components/messages/campaign-published-prod'
      campaign-disabled:
        $ref: '#/components/messages/campaign-disabled'

components:
  messages:
    client-published-int:
      name: client-published-int
      title: Client INT
      summary: "A client configuration targeted at INT has been published."
      contentType: application/json
      payload:
        allOf:
          - $ref: './cloud-events-envelope-1.0.yaml'
          - $ref: './events/client-published-int.yaml'
      examples:
        - payload:
            $ref: './examples/client-int.json'
    client-published-prod:
      name: client-published-prod
      title: Client PROD
      summary: "A client configuration targeted at PROD has been published."
      contentType: application/json
      payload:
        allOf:
          - $ref: './cloud-events-envelope-1.0.yaml'
          - $ref: './events/client-published-prod.yaml'
    client-disabled:
      name: client-disabled
      title: Client Disabled
      summary: "A client configuration has been disabled in all environments."
      contentType: application/json
      payload:
        allOf:
          - $ref: './cloud-events-envelope-1.0.yaml'
          - $ref: './events/client-disabled.yaml'
    campaign-published-int:
      name: campaign-published-int
      title: Campaign INT
      summary: "A campaign configuration targeted at INT has been published."
      contentType: application/json
      payload:
        allOf:
          - $ref: './cloud-events-envelope-1.0.yaml'
          - $ref: './events/campaign-published-int.yaml'
    campaign-published-prod:
      name: campaign-published-prod
      title: Campaign PROD
      summary: "A campaign configuration targeted at PROD has been published."
      contentType: application/json
      payload:
        allOf:
          - $ref: './cloud-events-envelope-1.0.yaml'
          - $ref: './events/campaign-published-prod.yaml'
    campaign-disabled:
      name: campaign-disabled
      title: Campaign Disabled
      summary: "A campaign configuration has been disabled in all environments."
      contentType: application/json
      payload:
        allOf:
          - $ref: './cloud-events-envelope-1.0.yaml'
          - $ref: './events/campaign-disabled.yaml'
