type: "object"
title: Client Config Published Event
additionalProperties: false
description: "Client configuration published event schema v1.0.0"
properties:
  data:
    $ref: "../domain/client.yaml"
  dataschema:
    pattern: "^https:\\/\\/notify\\.nhs\\.uk\\/events\\/schemas\\/client-changed\\/1.\\d+\\.\\d+\\.json$"
    type: "string"
  dataschemaversion:
    pattern: "^1\\.\\d+\\.\\d+$"
    type: "string"
  plane:
    const: "control"
    type: "string"
  type:
    const: "uk.nhs.notify.config.ClientChanged.v1"
    type: "string"
required:
  - "data"
  - "dataschema"
  - "dataschemaversion"
  - "type"
  - "plane"
