name: PR Destroy Environment

on:
  pull_request:
    types: [closed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  destroy-dynamic-environment:
    name: Destroy Dynamic Environment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5.0.0

      - name: Trigger dynamic environment destruction
        env:
          PR_TRIGGER_PAT: ${{ secrets.PR_TRIGGER_PAT }}
        shell: bash
        run: |
          .github/scripts/dispatch_internal_repo_workflow.sh \
            --infraRepoName "$(echo ${{ github.repository }} | cut -d'/' -f2)" \
            --releaseVersion "main" \
            --targetWorkflow "dispatch-deploy-dynamic-env.yaml" \
            --targetEnvironment "pr${{ github.event.number }}" \
            --targetComponent "ccbranch" \
            --targetAccountGroup "nhs-notify-client-config-dev" \
            --terraformAction "destroy" \
            --overrideProjectName "nhs" \
            --overrideRoleName "nhs-main-acct-client-config-github-deploy"
